### ISSUE TITLE
Typo in this repo's description

### ISSUE THREAD

**Issue by MaximeKjaer** [vincenzobaz/PracticeWithPullRequest#2]
The description of this repo is currently:

> Dummy repository to play a little with Githib's Pull Requests and Issues

GitHub is misspelled and miscapitalized. This was fixed in #1, but the issue still remains with the description. What are you thinking, Vince? Scandaloso :angry: 

You wanted some dummy issues, right?

**Comment by vincenzobaz** [comment]
Sorry for insulting your eight tentacled god!

**Comment by MaximeKjaer** [comment]
:crown: Apology accepted. You may now go on with your day, measly peasant.
